### ISSUE TITLE
Wont even find the avatar now

### ISSUE THREAD

**Issue by WhaleMaster** [bhaptics/VRChatOSC#13]
Just downloaded the new bhapticsOSC v1.1.0 was excited cause it says you guys fixed the constant motor issue and it now has OSC Query. But whenever I Try to use it it connects to vrchat client but doesn't see an avatar name or Id and won't work in game
![bhaptics](https://github.com/user-attachments/assets/7685aeaf-2ba2-47b0-82cc-9d4b13de5ea2)

**Comment by auejin** [comment]
Thanks for reporting the issue! We will try to reproduce this error and fix this asap. 

1. Could you check if [the OSC is enabled](https://docs.vrchat.com/docs/osc-overview#enabling-it) in your avatar?
2. Could you check if this also occurrs when using the default avatar provided by VRChat or our bHaptics World?

**Comment by WhaleMaster** [comment]
![image](https://github.com/user-attachments/assets/3201bad2-2de6-4c07-b219-1e75340ecc81)
![image](https://github.com/user-attachments/assets/42a33f62-58a9-469a-b044-dd66fef74d22)
It seems like the only working avatars are the ones uploaded by bhaptics inc, once I changed into any of the ones uploaded by bhaptics inc it starts seeing the name and id of any avatar I change into but it still doesn't work, except for the ones uploaded by bhaptics inc. I even tried to see if just having the word bhaptics in the name did anything but it still didn't

and yes I tried going into the default robot avatar and it still didn't show the name and id until I switched into a Bhaptics inc avatar

- [ ]

**Comment by auejin** [comment]
There can be many reasons for not being able to find the avatar, but the most frequent reason is not enabling OSC for the avatar you have chosen. Could change into your avatar and open the action menu so that you can enable the OSC toggle?

![image](https://github.com/user-attachments/assets/4376590f-b614-4427-946c-94f4fa0d623e)

Also, could you upload the full log text file here? You can click `Open Log` button at the bottom left of the window to locate the log text file. It will help us a lot for debugging the issue!

**Comment by WhaleMaster** [comment]
![image](https://github.com/user-attachments/assets/ae65bd34-77ee-4b8b-bde2-50ed7475a098)
![image](https://github.com/user-attachments/assets/d8e0a816-45b7-4e9c-8ef3-c605ca4827cd)
[bhaptics-osc.log](https://github.com/user-attachments/files/16466391/bhaptics-osc.log)
ask you can see yes I do have OSC enabled it only works on Bhaptic inc avatars

**Comment by auejin** [comment]
Hello! We just fixed minor bugs related to fetching avatar names and id. Could you test [our latest release (v1.1.1)](https://github.com/bhaptics/VRChatOSC/releases/tag/v1.1.1) and check if the haptics are available in your avatar?

**Comment by WhaleMaster** [comment]
ok so it seems it still wont see the old Parameters on any of my avatars, I tested by updating the avatar with the latest bhaptics osc avatar integrator and it seemed to work. though any of my old avatars still wont work unless I were to go back and update them all
it does see the name and id now
Old Parameter:
![image](https://github.com/user-attachments/assets/55087261-27bd-425f-b6d9-cf6da68f27a4)
New Parameter:
![image](https://github.com/user-attachments/assets/9f3d24c0-890e-46b9-9285-ff2458f7605b)

to summarize the software can only see the new parameters and not the old ones

Old Parameters:
bHapticsOSC_Vest_Front_1
bHapticsOSC_Vest_Front_2
bHapticsOSC_Vest_Front_3
bHapticsOSC_Vest_Front_4
bHapticsOSC_Vest_Front_5
bHapticsOSC_Vest_Front_6
bHapticsOSC_Vest_Front_7
bHapticsOSC_Vest_Front_8
bHapticsOSC_Vest_Front_9
bHapticsOSC_Vest_Front_10
bHapticsOSC_Vest_Front_11
bHapticsOSC_Vest_Front_12
bHapticsOSC_Vest_Front_13
bHapticsOSC_Vest_Front_14
bHapticsOSC_Vest_Front_15
bHapticsOSC_Vest_Front_16
bHapticsOSC_Vest_Front_17
bHapticsOSC_Vest_Front_18
bHapticsOSC_Vest_Front_19
bHapticsOSC_Vest_Front_20
bHapticsOSC_Vest_Back_1
bHapticsOSC_Vest_Back_2
bHapticsOSC_Vest_Back_3
bHapticsOSC_Vest_Back_4
bHapticsOSC_Vest_Back_5
bHapticsOSC_Vest_Back_6
bHapticsOSC_Vest_Back_7
bHapticsOSC_Vest_Back_8
bHapticsOSC_Vest_Back_9
bHapticsOSC_Vest_Back_10
bHapticsOSC_Vest_Back_11
bHapticsOSC_Vest_Back_12
bHapticsOSC_Vest_Back_13
bHapticsOSC_Vest_Back_14
bHapticsOSC_Vest_Back_15
bHapticsOSC_Vest_Back_16
bHapticsOSC_Vest_Back_17
bHapticsOSC_Vest_Back_18
bHapticsOSC_Vest_Back_19
bHapticsOSC_Vest_Back_20

**Comment by auejin** [comment]
Really glad to hear that the avatar works with our modern avatar configurator.
It seems like the parameters were first configured using Herp avatars!

[I just published the hot fix in the v1.1.2](https://github.com/bhaptics/VRChatOSC/releases/tag/v1.1.2). It should now be able to detect all the parameters from Herp avatars.
Thank you for taking your time and helping us to debug this issue!
